### ISSUE TITLE
duckdb.duckdb.ConversionException: Conversion Error: Could not convert string '\N' to FLOAT

### ISSUE THREAD

**Issue by julien-duponchelle** [julien-duponchelle/colvert#17]
### Description

Crash when running an SQL  query

### What I Did

With the IMDB dataset:
```
SELECT AVG(CAST(runtimeMinutes AS FLOAT)) AS average_runtime
FROM title_basics
WHERE titleType = 'movie' AND startYear = '2023';
```

The error
```
19:54:04 Error handling request
Traceback (most recent call last):
  File "/home/julien/.local/share/hatch/env/virtual/colvert/CLL0qgvt/colvert/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/.local/share/hatch/env/virtual/colvert/CLL0qgvt/colvert/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/.local/share/hatch/env/virtual/colvert/CLL0qgvt/colvert/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/.local/share/hatch/env/virtual/colvert/CLL0qgvt/colvert/lib/python3.12/site-packages/aiohttp_jinja2/__init__.py", line 264, in context_processors_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/code/colvert/colvert/ui/routes/results.py", line 46, in index
    return await render_full(chart_type, request, result, options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/code/colvert/colvert/ui/routes/results.py", line 60, in render_full
    body = await render_chart( chart_type, request, result,options, col=12)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/code/colvert/colvert/ui/routes/results.py", line 67, in render_chart
    body = await getattr(charts, chart)(request, result, options).build()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/code/colvert/colvert/ui/charts/base.py", line 59, in build
    self._validate()
  File "/home/julien/code/colvert/colvert/ui/charts/base.py", line 53, in _validate
    self._df = self._result.limit(self.limit + 1).df()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/julien/code/colvert/colvert/database.py", line 46, in df
    return self.result.df()
duckdb.duckdb.ConversionException: Conversion Error: Could not convert string '\N' to FLOAT
``

**Comment by julien-duponchelle** [comment]
Could be duplicate of https://github.com/julien-duponchelle/colvert/issues/13
